version: "3.7"
services:
  # Server
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:5000
    command: flask --app app run --host 0.0.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
  dashboard:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:5000
    command: flask --app dashboard run --host 0.0.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
